name: MOLECULE TEST

on:
  workflow_call:

jobs:
  molecule-test:
    name: Molecule test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install and config Libvirt, Vagrant and QEMU
        run: .github/workflows/scripts/ubuntu-setup.sh

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${ matrix.distro:-fedora37 }
