name: MOLECULE TEST

on:
  workflow_call:

jobs:
  molecule-test:
    name: Molecule test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

#      - name: Install and config Libvirt, Vagrant and QEMU
#        run: .github/workflows/scripts/ubuntu-setup.sh

      - name: Install Libvirt, Vagrant and QEMU
        run: |
          set -euxo pipefail
          sudo apt-get purge vagrant-libvirt
          sudo apt-mark hold vagrant-libvirt
          sudo apt-get update && \
          sudo apt-get install -y qemu libvirt-daemon-system ebtables libguestfs-tools \
          vagrant ruby-fog-libvirt

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${ matrix.distro:-fedora37 }
