---

name: RELEASE

'on':
  push:
    branches:
      - main
  workflow_call:

#permissions:
#  contents: read # for checkout

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SEMANTIC_RELEASE_PACKAGES: ${{ env.SEMANTIC_RELEASE_PACKAGES != '' && env.SEMANTIC_RELEASE_PACKAGES || '@semantic-release/github' }}

jobs:
  release:
    permissions:
      contents: write
#      issues: write # to be able to comment on released issues
#      pull-requests: write # to be able to comment on released pull requests
#      id-token: write # to enable use of OIDC for npm provenance
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install ${{ env.SEMANTIC_RELEASE_PACKAGES }} -D

      - name: Release
        run: npx semantic-release
