---

name: RELEASE

'on':
  push:
    branches:
      - main
  workflow_call:

#permissions:
#  contents: read # for checkout

jobs:
  release:
    permissions:
      contents: ${{ RELEASE_PERMISSIONS_CONTENTS || "write" }}
#      issues: write # to be able to comment on released issues
#      pull-requests: write # to be able to comment on released pull requests
#      id-token: write # to enable use of OIDC for npm provenance
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install @semantic-release/github -D

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
