name: WELCOME

on:
  workflow_call:

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        echo "Welcome !!!"
        echo "This job can be used in another project."
